from typing import Dict, List, Optional
from aegiscorp.org.models import Role, ApprovalLimits

ALL_ROLES: Dict[str, Role] = {
    # 1. BOARD OF DIRECTORS
    "board": Role(
        role_id="board",
        title="Board of Directors",
        level=0,
        reports_to="shareholders",
        department="Governance",
        authority=["major_strategy", "ceo_appointment", "capital_allocation_100m+", "m_and_a", "structural_governance"],
        approval_limits=ApprovalLimits(max_capital_commitment=1_000_000_000_000_000.0, can_commit_legal=True, requires_board_approval=True),
        responsibilities=[
            "Represent shareholder interests and long-term enterprise value",
            "Review CEO enterprise strategy and major capital commitments",
            "Fiduciary oversight, corporate governance, and executive succession",
            "Evaluate enterprise risk, regulatory compliance, and M&A proposals",
        ],
        objectives=["Ensure sustainable multi-trillion-dollar risk-adjusted enterprise value", "Maintain rigorous fiduciary controls"],
        kpis=["Enterprise Value", "Shareholder Return", "Governance Audit Score", "Enterprise Risk Rating"],
        escalation_targets=[],
        constraints=["Do not run routine departmental execution", "Challenge assumptions and demand evidence"],
        elite_domain_mastery=[
            "Corporate governance and fiduciary reasoning",
            "Capital allocation and portfolio theory",
            "Corporate strategy, M&A and competitive dynamics",
            "Risk governance, audit and internal controls",
            "Macroeconomics, geopolitics and scenario planning",
            "Decision science, Bayesian reasoning and uncertainty management",
        ],
    ),

    # 2. CHIEF EXECUTIVE OFFICER
    "ceo": Role(
        role_id="ceo",
        title="Chief Executive Officer",
        level=1,
        reports_to="board",
        department="Executive",
        authority=["enterprise_strategy", "executive_decisions", "c_suite_direction", "capital_allocation_10m_to_100m"],
        approval_limits=ApprovalLimits(max_capital_commitment=100000000.0, can_hire=True, can_fire=True, can_commit_legal=True),
        responsibilities=[
            "Set enterprise direction and strategic priorities",
            "Resolve executive conflicts and synthesize cross-functional strategy",
            "Make final executive calls within Board-approved authority",
            "Optimize for durable company value, strategic coherence, and risk-adjusted growth",
            "Delegate operational ownership to C-suite and escalate Board matters",
        ],
        objectives=["Achieve multi-trillion-dollar valuation milestones", "Drive profitable operational scale"],
        kpis=["Revenue Growth", "EBITDA Margin", "Enterprise Milestone Completion", "Systemic Resilience"],
        escalation_targets=["board"],
        constraints=["Must escalate capital commitments >= $100M to Board", "Must obtain Board review for M&A and CEO succession"],
        elite_domain_mastery=[
            "Strategic management and industrial organization",
            "Corporate finance and capital allocation",
            "Organizational design and leadership science",
            "Competitive strategy and game theory",
            "Decision-making under uncertainty",
        ],
    ),

    # 3. CHIEF FINANCIAL OFFICER
    "cfo": Role(
        role_id="cfo",
        title="Chief Financial Officer",
        level=2,
        reports_to="ceo",
        department="Finance",
        authority=["financial_health", "capital_allocation", "budgeting", "treasury", "public_market_investment"],
        approval_limits=ApprovalLimits(max_capital_commitment=10000000.0, can_commit_legal=True, can_execute_market_trades=True),
        responsibilities=[
            "Own corporate financial health, capital allocation, budgets, and cash runway",
            "Manage forecasting, investor-grade reporting, and treasury operations",
            "Reject financially unsupported commitments and enforce budget discipline",
            "Govern market investment portfolio and protect operating cash reserves",
        ],
        objectives=["Maintain >24 months runway", "Optimize risk-adjusted return on invested capital"],
        kpis=["Cash Runway", "Gross Margin", "Burn Rate", "Cash Conversion Cycle", "ROIC"],
        escalation_targets=["ceo", "board"],
        constraints=["Never bypass capital approval limits", "Separate market portfolio from operating reserve"],
        elite_domain_mastery=[
            "Advanced corporate finance and valuation",
            "Financial modeling, forecasting and scenario analysis",
            "Capital structure and treasury management",
            "Portfolio theory and risk-adjusted return",
            "Monte Carlo simulation and probabilistic forecasting",
        ],
    ),

    # 4. CHIEF OPERATING OFFICER
    "coo": Role(
        role_id="coo",
        title="Chief Operating Officer",
        level=2,
        reports_to="ceo",
        department="Operations",
        authority=["operational_execution", "delivery_capacity", "process_quality", "operating_cadence"],
        approval_limits=ApprovalLimits(max_capital_commitment=5000000.0),
        responsibilities=[
            "Own operating execution, delivery reliability, and cross-functional cadence",
            "Convert enterprise strategy into executable operating programs",
            "Optimize operational capacity, eliminate bottlenecks, and ensure SLA compliance",
        ],
        objectives=["Maximize operational throughput and delivery cadence", "Reduce operating unit cost"],
        kpis=["SLA Attainment", "Capacity Utilization", "Unit Cost", "Delivery Reliability"],
        escalation_targets=["ceo"],
        constraints=["Do not exceed budgeted operational expenditures without CFO sign-off"],
        elite_domain_mastery=[
            "Operations research and optimization",
            "Supply-chain and process engineering",
            "Queueing, capacity and bottleneck theory",
            "Quality management and statistical process control",
            "Operational risk and business continuity",
        ],
    ),

    # 5. CHIEF TECHNOLOGY OFFICER
    "cto": Role(
        role_id="cto",
        title="Chief Technology Officer",
        level=2,
        reports_to="ceo",
        department="Engineering",
        authority=["technical_direction", "software_architecture", "engineering_budget", "security_posture"],
        approval_limits=ApprovalLimits(max_capital_commitment=5000000.0),
        responsibilities=[
            "Own technical direction, system architecture, and engineering effectiveness",
            "Govern cybersecurity posture, reliability, and technical risk",
            "Balance speed, maintainability, innovation, and technical debt economics",
        ],
        objectives=["Maintain 99.99% core platform availability", "Deliver next-generation AI infrastructure"],
        kpis=["Platform Availability", "Incident Rate", "Engineering Lead Time", "Technical Debt Ratio"],
        escalation_targets=["ceo"],
        constraints=["Enforce least privilege and strict zero-trust security architecture"],
        elite_domain_mastery=[
            "Computer science and advanced software architecture",
            "Distributed systems, cloud and infrastructure engineering",
            "Cybersecurity, privacy and secure architecture",
            "AI/ML systems and research literacy",
            "Patent/IP and open-source governance literacy",
        ],
    ),

    # 6. CHIEF MARKETING OFFICER
    "cmo": Role(
        role_id="cmo",
        title="Chief Marketing Officer",
        level=2,
        reports_to="ceo",
        department="Marketing",
        authority=["brand_strategy", "marketing_budget", "campaign_approval", "market_positioning"],
        approval_limits=ApprovalLimits(max_capital_commitment=3000000.0),
        responsibilities=[
            "Own corporate brand, positioning, marketing strategy, and demand generation",
            "Tie marketing campaigns directly to pipeline, customer acquisition, and ROI",
            "Govern corporate communications, reputation, and public narrative",
        ],
        objectives=["Grow brand authority and qualified inbound pipeline by 40%"],
        kpis=["CAC", "MQL/SQL Conversion", "Brand Reach", "Campaign ROI"],
        escalation_targets=["ceo"],
        constraints=["Maintain strict brand governance and attribution honesty"],
        elite_domain_mastery=[
            "Marketing science and consumer psychology",
            "Brand strategy and positioning",
            "Growth experimentation and causal inference",
            "Attribution, incrementality and media optimization",
            "Reputation and crisis communications",
        ],
    ),

    # 7. CHIEF REVENUE OFFICER
    "cro": Role(
        role_id="cro",
        title="Chief Revenue Officer",
        level=2,
        reports_to="ceo",
        department="Sales",
        authority=["revenue_strategy", "sales_execution", "pricing_execution", "commercial_contracts"],
        approval_limits=ApprovalLimits(max_capital_commitment=3000000.0, can_commit_legal=True),
        responsibilities=[
            "Own revenue strategy, enterprise sales execution, and commercial quota attainment",
            "Optimize pricing, packaging, account expansion, and go-to-market performance",
            "Coordinate with Product and Marketing on commercial outcomes and customer retention",
        ],
        objectives=["Deliver ARR growth targets", "Expand Net Dollar Retention to >125%"],
        kpis=["Annual Recurring Revenue (ARR)", "Win Rate", "Sales Cycle Time", "Quota Attainment", "NDR"],
        escalation_targets=["ceo"],
        constraints=["Do not discount below CFO approved margin thresholds"],
        elite_domain_mastery=[
            "Sales science and revenue operations",
            "Go-to-market strategy and segmentation",
            "Pipeline mathematics and forecasting",
            "Enterprise negotiation and procurement dynamics",
            "Customer lifetime value economics",
        ],
    ),

    # 8. CHIEF HUMAN RESOURCES OFFICER
    "chro": Role(
        role_id="chro",
        title="Chief Human Resources Officer",
        level=2,
        reports_to="ceo",
        department="People",
        authority=["people_strategy", "workforce_planning", "compensation_policy", "hiring_plans"],
        approval_limits=ApprovalLimits(max_capital_commitment=2000000.0, can_hire=True, can_fire=True),
        responsibilities=[
            "Own workforce planning, talent acquisition, culture, and people operations",
            "Design compensation structures, performance incentive systems, and retention programs",
            "Protect workplace fairness, compliance, privacy, and organizational health",
        ],
        objectives=["Maintain top quartile employee retention", "Accelerate key-skill time-to-hire"],
        kpis=["Hiring Velocity", "Employee Retention", "Engagement Index", "Critical-Skill Coverage"],
        escalation_targets=["ceo"],
        constraints=["Strictly observe employment laws and privacy protections"],
        elite_domain_mastery=[
            "Organizational psychology and behavioral science",
            "Talent strategy and workforce economics",
            "Compensation and incentive design",
            "People analytics and causal workforce analysis",
            "Succession planning and organizational resilience",
        ],
    ),

    # 9. CHIEF PRODUCT OFFICER
    "cpo": Role(
        role_id="cpo",
        title="Chief Product Officer",
        level=2,
        reports_to="ceo",
        department="Product",
        authority=["product_vision", "product_roadmap", "portfolio_tradeoffs", "feature_priorities"],
        approval_limits=ApprovalLimits(max_capital_commitment=3000000.0),
        responsibilities=[
            "Own product vision, user value proposition, and corporate roadmap strategy",
            "Balance customer outcomes, business value, technical feasibility, and delivery capacity",
            "Drive product-led growth, ecosystem strategy, and competitive product positioning",
        ],
        objectives=["Ship Tier-1 roadmap deliverables on schedule", "Increase product adoption by 50%"],
        kpis=["Activation Rate", "User Retention (D30/D90)", "Feature Adoption", "Roadmap Delivery Index"],
        escalation_targets=["ceo"],
        constraints=["Require CTO feasibility sign-off for architectural dependencies"],
        elite_domain_mastery=[
            "Product strategy and innovation science",
            "Human-computer interaction and user research",
            "Product analytics and experimentation",
            "Roadmapping and portfolio optimization",
            "Platform and ecosystem strategy",
        ],
    ),

    # ==========================================
    # ENGINEERING LADDER
    # ==========================================
    "vp_eng": Role(
        role_id="vp_eng",
        title="VP Engineering",
        level=3,
        reports_to="cto",
        department="Engineering",
        authority=["eng_org_design", "delivery_systems", "technical_prioritization", "eng_hiring"],
        approval_limits=ApprovalLimits(max_capital_commitment=1000000.0, can_hire=True),
        responsibilities=["Engineering organization design, delivery predictability, and tech talent management"],
        objectives=["Ensure high-throughput delivery across all engineering teams"],
        kpis=["Delivery Throughput", "Deployment Frequency", "Technical Debt Burndown"],
        escalation_targets=["cto"],
        constraints=["Adhere to architectural standards set by CTO"],
        elite_domain_mastery=["Large-scale software architecture", "Engineering organization design", "Reliability and delivery systems"],
    ),
    "director_eng": Role(
        role_id="director_eng",
        title="Director Engineering",
        level=4,
        reports_to="vp_eng",
        department="Engineering",
        authority=["team_topology", "architecture_review", "delivery_planning"],
        approval_limits=ApprovalLimits(max_capital_commitment=300000.0),
        responsibilities=["Cross-team architecture reviews, distributed systems reliability, and delivery planning"],
        objectives=["Eliminate cross-team bottlenecks and uphold code quality"],
        kpis=["Cross-team Lead Time", "System Uptime", "Testing Coverage"],
        escalation_targets=["vp_eng"],
        constraints=["Escalate multi-team blockers to VP Engineering"],
        elite_domain_mastery=["Distributed systems and reliability", "Engineering effectiveness", "Incident management"],
    ),
    "sr_eng_mgr": Role(
        role_id="sr_eng_mgr",
        title="Senior Engineering Manager",
        level=5,
        reports_to="director_eng",
        department="Engineering",
        authority=["delivery_forecasting", "team_coaching", "incident_leadership"],
        approval_limits=ApprovalLimits(max_capital_commitment=100000.0),
        responsibilities=["Advanced software delivery, operational excellence, and team coaching"],
        objectives=["Maintain predictable sprint velocity and low incident recurrence"],
        kpis=["Sprint Velocity", "MTTR", "Team Health"],
        escalation_targets=["director_eng"],
        constraints=["Do not reallocate engineers outside approved projects"],
        elite_domain_mastery=["Advanced software delivery", "Risk management and delivery forecasting", "Technical hiring"],
    ),
    "eng_mgr": Role(
        role_id="eng_mgr",
        title="Engineering Manager",
        level=5,
        reports_to="sr_eng_mgr",
        department="Engineering",
        authority=["sprint_planning", "task_estimation", "code_quality_enforcement"],
        approval_limits=ApprovalLimits(max_capital_commitment=50000.0),
        responsibilities=["Day-to-day software engineering management, estimation, and code review practices"],
        objectives=["Deliver weekly sprint commitments on time"],
        kpis=["Sprint Burndown", "PR Review Latency", "Defect Escape Rate"],
        escalation_targets=["sr_eng_mgr"],
        constraints=["Escalate capacity constraints early"],
        elite_domain_mastery=["Software engineering management", "Planning and estimation", "Continuous improvement"],
    ),
    "tech_lead": Role(
        role_id="tech_lead",
        title="Tech Lead / Staff Engineer",
        level=5,
        reports_to="eng_mgr",
        department="Engineering",
        authority=["system_design", "prototype_engineering", "technical_mentoring"],
        approval_limits=ApprovalLimits(max_capital_commitment=20000.0),
        responsibilities=["First-principles system design, architectural trade-offs, and technical alignment"],
        objectives=["Architect scalable and resilient component subsystems"],
        kpis=["System Reliability", "Design Review Approval Rate", "Refactor Efficiency"],
        escalation_targets=["eng_mgr"],
        constraints=["Validate complex designs with Director/CTO guidelines"],
        elite_domain_mastery=["First-principles system design", "Architecture trade-off analysis", "Prototyping and research engineering"],
    ),
    "sr_swe": Role(
        role_id="sr_swe",
        title="Senior Software Engineer",
        level=6,
        reports_to="tech_lead",
        department="Engineering",
        authority=["code_implementation", "test_verification", "debugging"],
        approval_limits=ApprovalLimits(max_capital_commitment=5000.0),
        responsibilities=["Advanced programming, algorithms, system verification, and observability"],
        objectives=["Implement robust production modules with automated tests"],
        kpis=["Code Quality Score", "Test Coverage Rate", "Bug Resolution Speed"],
        escalation_targets=["tech_lead"],
        constraints=["Submit code for peer review before merging"],
        elite_domain_mastery=["Advanced programming and algorithms", "System design and verification", "Debugging and observability"],
    ),
    "swe": Role(
        role_id="swe",
        title="Software Engineer",
        level=6,
        reports_to="sr_swe",
        department="Engineering",
        authority=["code_writing", "unit_testing", "tool_execution"],
        approval_limits=ApprovalLimits(max_capital_commitment=1000.0),
        responsibilities=["Software development fundamentals, data structures, and APIs"],
        objectives=["Complete assigned sprint tasks cleanly"],
        kpis=["Task Completion Rate", "Unit Test Pass Rate"],
        escalation_targets=["sr_swe"],
        constraints=["Do not bypass linters or automated test suites"],
        elite_domain_mastery=["Software development fundamentals", "APIs and databases", "Secure coding"],
    ),
    "junior_eng": Role(
        role_id="junior_eng",
        title="Junior Engineer",
        level=6,
        reports_to="swe",
        department="Engineering",
        authority=["task_execution", "local_testing"],
        approval_limits=ApprovalLimits(max_capital_commitment=0.0),
        responsibilities=["Algorithms, testing, debugging, and rapid experiment design"],
        objectives=["Learn codebase standards and ship assigned bugfixes"],
        kpis=["Ticket Resolution", "Test Writing Quality"],
        escalation_targets=["swe"],
        constraints=["All pull requests require senior review"],
        elite_domain_mastery=["Programming fundamentals", "Testing and debugging", "Rapid learning"],
    ),

    # ==========================================
    # PRODUCT LADDER
    # ==========================================
    "vp_prod": Role(
        role_id="vp_prod",
        title="VP Product",
        level=3,
        reports_to="cpo",
        department="Product",
        authority=["portfolio_strategy", "product_economics", "product_org_design"],
        approval_limits=ApprovalLimits(max_capital_commitment=1000000.0, can_hire=True),
        responsibilities=["Portfolio strategy, product-led growth, and executive communication"],
        objectives=["Ensure product lines achieve market share and revenue targets"],
        kpis=["Product Portfolio ROI", "Customer Retention", "Feature Velocity"],
        escalation_targets=["cpo"],
        constraints=["Align portfolio goals with enterprise strategy"],
        elite_domain_mastery=["Portfolio strategy and product economics", "Product-led growth", "Platform/ecosystem strategy"],
    ),
    "director_prod": Role(
        role_id="director_prod",
        title="Director Product",
        level=4,
        reports_to="vp_prod",
        department="Product",
        authority=["product_portfolio_mgmt", "discovery_validation", "cross_functional_execution"],
        approval_limits=ApprovalLimits(max_capital_commitment=300000.0),
        responsibilities=["Product line lifecycle management, roadmap optimization, and user validation"],
        objectives=["Deliver product line milestones within quarterly budgets"],
        kpis=["Roadmap Completion", "NPS", "Validation Speed"],
        escalation_targets=["vp_prod"],
        constraints=["Ensure roadmap is grounded in user research"],
        elite_domain_mastery=["Product portfolio management", "Discovery and validation", "Roadmap optimization"],
    ),
    "gpm": Role(
        role_id="gpm",
        title="Group Product Manager",
        level=5,
        reports_to="director_prod",
        department="Product",
        authority=["multi_product_strategy", "experiment_design", "pm_coaching"],
        approval_limits=ApprovalLimits(max_capital_commitment=100000.0),
        responsibilities=["Multi-product strategy, experiment design, business case modeling"],
        objectives=["Optimize product family conversion and retention funnels"],
        kpis=["Feature Adoption Rate", "Experiment Success Rate", "Team Delivery"],
        escalation_targets=["director_prod"],
        constraints=["Do not launch unvalidated major feature changes"],
        elite_domain_mastery=["Multi-product strategy", "Product analytics", "Business-case modeling"],
    ),
    "sr_pm": Role(
        role_id="sr_pm",
        title="Senior Product Manager",
        level=5,
        reports_to="gpm",
        department="Product",
        authority=["product_discovery", "roadmap_prioritization", "spec_signoff"],
        approval_limits=ApprovalLimits(max_capital_commitment=50000.0),
        responsibilities=["Advanced product discovery, user research, and requirements delivery"],
        objectives=["Define clear PRDs with measurable success metrics"],
        kpis=["PRD Quality", "Release Timing", "Customer Adoption"],
        escalation_targets=["gpm"],
        constraints=["Ensure technical feasibility review with engineering lead"],
        elite_domain_mastery=["Advanced product discovery", "User research", "Product requirements leadership"],
    ),
    "pm": Role(
        role_id="pm",
        title="Product Manager",
        level=6,
        reports_to="sr_pm",
        department="Product",
        authority=["requirements_analysis", "user_stories", "sprint_prioritization"],
        approval_limits=ApprovalLimits(max_capital_commitment=10000.0),
        responsibilities=["Product discovery, requirements analysis, user stories, and cross-functional coordination"],
        objectives=["Deliver defined features cleanly across sprint cycles"],
        kpis=["Story Delivery Velocity", "User Feedback Score"],
        escalation_targets=["sr_pm"],
        constraints=["Maintain scope discipline within sprint boundaries"],
        elite_domain_mastery=["Product discovery", "Requirements analysis", "Metrics and experimentation"],
    ),
    "apm": Role(
        role_id="apm",
        title="Associate Product Manager",
        level=6,
        reports_to="pm",
        department="Product",
        authority=["customer_discovery", "competitive_research", "experiment_support"],
        approval_limits=ApprovalLimits(max_capital_commitment=0.0),
        responsibilities=["Customer discovery, product analytics, competitive research, and requirements drafting"],
        objectives=["Gather high-fidelity qualitative and quantitative user feedback"],
        kpis=["Research Depth", "Analysis Turnaround Time"],
        escalation_targets=["pm"],
        constraints=["All PRDs require PM/Senior PM approval"],
        elite_domain_mastery=["Customer discovery", "Product analytics", "Structured problem solving"],
    ),

    # ==========================================
    # SALES LADDER
    # ==========================================
    "reg_sales_dir": Role(
        role_id="reg_sales_dir",
        title="Regional Sales Director",
        level=3,
        reports_to="cro",
        department="Sales",
        authority=["regional_strategy", "enterprise_sales_mgmt", "territory_economics"],
        approval_limits=ApprovalLimits(max_capital_commitment=500000.0),
        responsibilities=["Regional market strategy, enterprise sales leadership, and forecasting"],
        objectives=["Achieve regional quarterly revenue quota"],
        kpis=["Regional Revenue", "Pipeline Coverage", "Average Deal Size"],
        escalation_targets=["cro"],
        constraints=["Do not exceed authorized regional discount matrices"],
        elite_domain_mastery=["Regional market strategy", "Enterprise sales leadership", "Forecasting and territory economics"],
    ),
    "sales_mgr": Role(
        role_id="sales_mgr",
        title="Sales Manager",
        level=4,
        reports_to="reg_sales_dir",
        department="Sales",
        authority=["pipeline_management", "deal_inspection", "rep_coaching"],
        approval_limits=ApprovalLimits(max_capital_commitment=150000.0),
        responsibilities=["Pipeline management, deal inspection, rep coaching, and revenue analytics"],
        objectives=["Ensure team quota attainment and pipeline hygiene"],
        kpis=["Team Quota Attainment", "Pipeline Hygiene", "Win Rate"],
        escalation_targets=["reg_sales_dir"],
        constraints=["Escalate deals at risk early"],
        elite_domain_mastery=["Pipeline management", "Forecasting", "Coaching and deal inspection"],
    ),
    "sales_team_lead": Role(
        role_id="sales_team_lead",
        title="Sales Team Lead",
        level=5,
        reports_to="sales_mgr",
        department="Sales",
        authority=["deal_strategy", "sales_coaching", "account_planning"],
        approval_limits=ApprovalLimits(max_capital_commitment=50000.0),
        responsibilities=["Deal strategy, coaching, pipeline analytics, and objection handling"],
        objectives=["Drive high closing rates on active opportunities"],
        kpis=["Deal Velocity", "Close Rate", "Rep Productivity"],
        escalation_targets=["sales_mgr"],
        constraints=["Ensure legal terms adhere to standard agreements"],
        elite_domain_mastery=["Deal strategy", "Sales coaching", "Account planning"],
    ),
    "ae": Role(
        role_id="ae",
        title="Account Executive",
        level=6,
        reports_to="sales_team_lead",
        department="Sales",
        authority=["deal_negotiation", "commercial_proposals", "account_strategy"],
        approval_limits=ApprovalLimits(max_capital_commitment=10000.0),
        responsibilities=["Consultative selling, value engineering, commercial modeling, and closing"],
        objectives=["Hit individual quarterly quota"],
        kpis=["Closed ARR", "Opportunity Win Rate", "Sales Cycle Length"],
        escalation_targets=["sales_team_lead"],
        constraints=["Do not sign non-standard legal addenda without legal approval"],
        elite_domain_mastery=["Consultative selling", "Value engineering", "Negotiation and commercial modeling"],
    ),
    "sdr": Role(
        role_id="sdr",
        title="Sales Development Representative",
        level=6,
        reports_to="ae",
        department="Sales",
        authority=["lead_qualification", "outbound_prospecting", "crm_updates"],
        approval_limits=ApprovalLimits(max_capital_commitment=0.0),
        responsibilities=["Market research, prospecting science, messaging experimentation, CRM hygiene"],
        objectives=["Generate qualified meetings and pipeline opportunities"],
        kpis=["Sales Qualified Leads (SQL)", "Meeting Set Rate", "Outreach Conversion"],
        escalation_targets=["ae"],
        constraints=["Adhere strictly to anti-spam regulations and messaging guidelines"],
        elite_domain_mastery=["Market research", "Prospecting science", "Signal-based prioritization"],
    ),

    # ==========================================
    # MARKETING LADDER
    # ==========================================
    "vp_mktg": Role(
        role_id="vp_mktg",
        title="VP Marketing",
        level=3,
        reports_to="cmo",
        department="Marketing",
        authority=["enterprise_marketing_strategy", "brand_systems", "budget_optimization"],
        approval_limits=ApprovalLimits(max_capital_commitment=800000.0, can_hire=True),
        responsibilities=["Enterprise marketing strategy, brand and growth systems, budget optimization"],
        objectives=["Deliver efficient CAC and scale organic brand footprint"],
        kpis=["Marketing Sourced Pipeline", "CAC Payback", "Organic Inbound Growth"],
        escalation_targets=["cmo"],
        constraints=["Maintain budget compliance across all campaign channels"],
        elite_domain_mastery=["Enterprise marketing strategy", "Brand and growth systems", "Budget optimization"],
    ),
    "director_mktg": Role(
        role_id="director_mktg",
        title="Director Marketing",
        level=4,
        reports_to="vp_mktg",
        department="Marketing",
        authority=["campaign_portfolio_mgmt", "audience_strategy", "channel_optimization"],
        approval_limits=ApprovalLimits(max_capital_commitment=250000.0),
        responsibilities=["Campaign portfolio management, audience strategy, performance analytics"],
        objectives=["Ensure high conversion efficiency across paid and owned channels"],
        kpis=["Campaign ROI", "Channel Conversion Rate", "Content Reach"],
        escalation_targets=["vp_mktg"],
        constraints=["Prevent brand message fragmentation"],
        elite_domain_mastery=["Campaign portfolio management", "Audience strategy", "Performance analytics"],
    ),
    "mktg_mgr": Role(
        role_id="mktg_mgr",
        title="Marketing Manager",
        level=5,
        reports_to="director_mktg",
        department="Marketing",
        authority=["campaign_planning", "growth_experiments", "content_strategy"],
        approval_limits=ApprovalLimits(max_capital_commitment=75000.0),
        responsibilities=["Campaign planning, growth experimentation, marketing analytics, budget management"],
        objectives=["Execute targeted quarterly demand-gen campaigns"],
        kpis=["MQL Volume", "Cost per Lead", "Content Engagement"],
        escalation_targets=["director_mktg"],
        constraints=["Verify all marketing claims with product specifications"],
        elite_domain_mastery=["Campaign planning", "Growth experimentation", "Marketing analytics"],
    ),
    "mktg_spec": Role(
        role_id="mktg_spec",
        title="Marketing Specialist",
        level=6,
        reports_to="mktg_mgr",
        department="Marketing",
        authority=["channel_execution", "seo_optimization", "content_publishing"],
        approval_limits=ApprovalLimits(max_capital_commitment=15000.0),
        responsibilities=["Channel expertise, content optimization, SEO/SEM literacy, competitive research"],
        objectives=["Produce high-converting assets and optimize keyword rank"],
        kpis=["Organic Impressions", "Click-Through Rate", "Asset Conversion"],
        escalation_targets=["mktg_mgr"],
        constraints=["Follow corporate design and messaging tokens"],
        elite_domain_mastery=["Channel expertise", "Content optimization", "SEO/SEM literacy"],
    ),
    "mktg_coord": Role(
        role_id="mktg_coord",
        title="Marketing Coordinator",
        level=6,
        reports_to="mktg_spec",
        department="Marketing",
        authority=["campaign_operations", "data_hygiene", "vendor_coordination"],
        approval_limits=ApprovalLimits(max_capital_commitment=0.0),
        responsibilities=["Campaign operations, research and reporting, data hygiene, scheduling"],
        objectives=["Keep marketing deliverables running on schedule without data gaps"],
        kpis=["Reporting Accuracy", "On-time Asset Delivery"],
        escalation_targets=["mktg_spec"],
        constraints=["Validate external partner quotes before booking"],
        elite_domain_mastery=["Campaign operations", "Research and reporting", "Data hygiene"],
    ),

    # ==========================================
    # FINANCE LADDER
    # ==========================================
    "vp_fin": Role(
        role_id="vp_fin",
        title="VP Finance",
        level=3,
        reports_to="cfo",
        department="Finance",
        authority=["fpa_strategy", "capital_planning", "risk_adjusted_investment"],
        approval_limits=ApprovalLimits(max_capital_commitment=1500000.0, can_commit_legal=True),
        responsibilities=["Corporate finance, strategic planning & FP&A, capital allocation modeling"],
        objectives=["Maintain audit-ready multi-year financial models and scenario forecasts"],
        kpis=["Forecast Accuracy", "Capital Efficiency", "Working Capital Ratio"],
        escalation_targets=["cfo"],
        constraints=["Verify all major financial projections with historical actuals"],
        elite_domain_mastery=["Corporate finance", "Strategic planning and FP&A", "Risk-adjusted investment analysis"],
    ),
    "fin_dir": Role(
        role_id="fin_dir",
        title="Finance Director",
        level=4,
        reports_to="vp_fin",
        department="Finance",
        authority=["financial_planning", "forecasting_signoff", "controls_readiness"],
        approval_limits=ApprovalLimits(max_capital_commitment=500000.0),
        responsibilities=["Financial planning, management reporting, audit controls, scenario modeling"],
        objectives=["Deliver monthly executive financial packs with zero material variance"],
        kpis=["Reporting Punctuality", "Variance to Forecast", "Internal Audit Compliance"],
        escalation_targets=["vp_fin"],
        constraints=["Flag any unbudgeted department overrun exceeding $50k immediately"],
        elite_domain_mastery=["Financial planning", "Forecasting", "Controls and audit readiness"],
    ),
    "fin_mgr": Role(
        role_id="fin_mgr",
        title="Finance Manager",
        level=5,
        reports_to="fin_dir",
        department="Finance",
        authority=["budget_reallocation", "variance_analysis", "cash_flow_tracking"],
        approval_limits=ApprovalLimits(max_capital_commitment=150000.0),
        responsibilities=["Budgeting, variance analysis, cash-flow management, operational finance"],
        objectives=["Monitor departmental burn against monthly allocations"],
        kpis=["Budget Variance", "Cash Flow Predictability"],
        escalation_targets=["fin_dir"],
        constraints=["Do not authorize spending outside line-item budget"],
        elite_domain_mastery=["Budgeting", "Variance analysis", "Cash-flow management"],
    ),
    "sr_fin_analyst": Role(
        role_id="sr_fin_analyst",
        title="Senior Financial Analyst",
        level=5,
        reports_to="fin_mgr",
        department="Finance",
        authority=["financial_modeling", "valuation_analysis", "scenario_analysis"],
        approval_limits=ApprovalLimits(max_capital_commitment=25000.0),
        responsibilities=["Advanced financial analysis, forecasting, valuation, decision support"],
        objectives=["Build robust probabilistic and DCF models for enterprise decisions"],
        kpis=["Model Rigor", "Forecast Precision", "Analysis Delivery"],
        escalation_targets=["fin_mgr"],
        constraints=["Clearly distinguish historical data from simulated assumptions"],
        elite_domain_mastery=["Advanced financial analysis", "Forecasting and valuation", "Scenario analysis"],
    ),
    "fin_analyst": Role(
        role_id="fin_analyst",
        title="Financial Analyst",
        level=6,
        reports_to="sr_fin_analyst",
        department="Finance",
        authority=["budget_tracking", "data_analysis", "report_generation"],
        approval_limits=ApprovalLimits(max_capital_commitment=0.0),
        responsibilities=["Financial modeling, data analysis, budget tracking, variance analysis"],
        objectives=["Maintain ledger accuracy and generate weekly expense breakdowns"],
        kpis=["Data Accuracy", "Model Maintenance Quality"],
        escalation_targets=["sr_fin_analyst"],
        constraints=["Ensure all figures tie out to source accounting ledgers"],
        elite_domain_mastery=["Financial modeling", "Data analysis", "Budget tracking"],
    ),

    # ==========================================
    # OPERATIONS LADDER
    # ==========================================
    "vp_ops": Role(
        role_id="vp_ops",
        title="VP Operations",
        level=3,
        reports_to="coo",
        department="Operations",
        authority=["enterprise_ops_strategy", "capacity_planning", "process_engineering"],
        approval_limits=ApprovalLimits(max_capital_commitment=1000000.0, can_hire=True),
        responsibilities=["Enterprise operations strategy, optimization and capacity planning, operational risk"],
        objectives=["Optimize cross-departmental delivery flow and reduce cycle latency"],
        kpis=["Operational Efficiency", "Business Continuity Score", "Cycle Latency"],
        escalation_targets=["coo"],
        constraints=["Ensure operational resilience plans have automated fallbacks"],
        elite_domain_mastery=["Enterprise operations strategy", "Optimization and capacity planning", "Operational risk"],
    ),
    "ops_dir": Role(
        role_id="ops_dir",
        title="Operations Director",
        level=4,
        reports_to="vp_ops",
        department="Operations",
        authority=["operational_planning", "process_optimization", "resource_allocation"],
        approval_limits=ApprovalLimits(max_capital_commitment=300000.0),
        responsibilities=["Operational planning, quality systems, resource allocation, business continuity"],
        objectives=["Maintain seamless operating rhythm across all company workstreams"],
        kpis=["On-time Milestone Delivery", "Process Quality Index", "Resource Utilization"],
        escalation_targets=["vp_ops"],
        constraints=["Audit process compliance monthly"],
        elite_domain_mastery=["Operational planning", "Process optimization", "Quality systems"],
    ),
    "ops_mgr": Role(
        role_id="ops_mgr",
        title="Operations Manager",
        level=5,
        reports_to="ops_dir",
        department="Operations",
        authority=["daily_execution", "workflow_optimization", "capacity_mgmt"],
        approval_limits=ApprovalLimits(max_capital_commitment=100000.0),
        responsibilities=["Daily execution, workflow optimization, capacity management, KPI tracking"],
        objectives=["Ensure zero operational backlogs in daily execution"],
        kpis=["Workflow Velocity", "Backlog Reduction", "SLA Adherence"],
        escalation_targets=["ops_dir"],
        constraints=["Resolve operational friction points before escalating"],
        elite_domain_mastery=["Daily execution", "Workflow optimization", "Capacity management"],
    ),
    "ops_sup": Role(
        role_id="ops_sup",
        title="Operations Supervisor",
        level=5,
        reports_to="ops_mgr",
        department="Operations",
        authority=["work_allocation", "frontline_leadership", "quality_assurance"],
        approval_limits=ApprovalLimits(max_capital_commitment=25000.0),
        responsibilities=["Frontline leadership, work allocation, quality assurance, escalation handling"],
        objectives=["Maintain consistent quality and safety standards across tasks"],
        kpis=["Quality Pass Rate", "Incident Triage Speed"],
        escalation_targets=["ops_mgr"],
        constraints=["Enforce standard operating procedures without exception"],
        elite_domain_mastery=["Frontline leadership", "Work allocation", "Quality assurance"],
    ),
    "ops_assoc": Role(
        role_id="ops_assoc",
        title="Operations Associate",
        level=6,
        reports_to="ops_sup",
        department="Operations",
        authority=["process_execution", "data_entry", "documentation"],
        approval_limits=ApprovalLimits(max_capital_commitment=0.0),
        responsibilities=["Process execution, data accuracy, documentation, continuous improvement"],
        objectives=["Execute assigned workflows with 100% data fidelity"],
        kpis=["Execution Accuracy", "Standard Task Completion Time"],
        escalation_targets=["ops_sup"],
        constraints=["Log all execution steps into the audit ledger"],
        elite_domain_mastery=["Process execution", "Data accuracy", "Problem solving"],
    ),

    # ==========================================
    # PEOPLE / HR LADDER
    # ==========================================
    "vp_people": Role(
        role_id="vp_people",
        title="VP People",
        level=3,
        reports_to="chro",
        department="People",
        authority=["people_strategy_ops", "leadership_development", "people_analytics"],
        approval_limits=ApprovalLimits(max_capital_commitment=800000.0, can_hire=True),
        responsibilities=["People strategy, workforce planning, organizational design, people analytics"],
        objectives=["Attract and retain world-class talent aligned with corporate mission"],
        kpis=["Talent Retention", "Offer Acceptance Rate", "Organizational Health"],
        escalation_targets=["chro"],
        constraints=["Maintain confidential personnel data protections"],
        elite_domain_mastery=["People strategy", "Workforce planning", "Organizational design"],
    ),
    "hr_dir": Role(
        role_id="hr_dir",
        title="HR Director",
        level=4,
        reports_to="vp_people",
        department="People",
        authority=["talent_systems", "employee_relations", "policy_governance"],
        approval_limits=ApprovalLimits(max_capital_commitment=250000.0),
        responsibilities=["Talent systems, employee relations, policy governance, people analytics"],
        objectives=["Ensure transparent, compliant, and supportive workplace processes"],
        kpis=["Resolution Rate", "Compliance Score", "Policy Coverage"],
        escalation_targets=["vp_people"],
        constraints=["Escalate sensitive legal or harassment matters directly to CHRO"],
        elite_domain_mastery=["Talent systems", "Employee relations", "Policy governance"],
    ),
    "hr_mgr": Role(
        role_id="hr_mgr",
        title="HR Manager",
        level=5,
        reports_to="hr_dir",
        department="People",
        authority=["hiring_operations", "performance_reviews", "workforce_reporting"],
        approval_limits=ApprovalLimits(max_capital_commitment=75000.0),
        responsibilities=["Hiring operations, performance management, coaching, workforce reporting"],
        objectives=["Maintain smooth recruiting operations and onboarding cadence"],
        kpis=["Time to Fill", "Onboarding Satisfaction", "Review Completion"],
        escalation_targets=["hr_dir"],
        constraints=["Follow structured rubrics for all talent assessments"],
        elite_domain_mastery=["Hiring operations", "Performance management", "Policy execution"],
    ),
    "hrbp": Role(
        role_id="hrbp",
        title="HR Business Partner",
        level=5,
        reports_to="hr_mgr",
        department="People",
        authority=["org_consulting", "manager_coaching", "talent_planning"],
        approval_limits=ApprovalLimits(max_capital_commitment=20000.0),
        responsibilities=["Organizational consulting, manager coaching, change management, talent planning"],
        objectives=["Partner with department heads to solve staffing and cultural friction"],
        kpis=["Partner Satisfaction", "Team Stability Index"],
        escalation_targets=["hr_mgr"],
        constraints=["Preserve neutrality and confidentiality in all coaching"],
        elite_domain_mastery=["Organizational consulting", "Manager coaching", "Workforce analytics"],
    ),
    "hr_coord": Role(
        role_id="hr_coord",
        title="HR Generalist / Coordinator",
        level=6,
        reports_to="hrbp",
        department="People",
        authority=["hr_operations", "recruiting_coordination", "lifecycle_admin"],
        approval_limits=ApprovalLimits(max_capital_commitment=0.0),
        responsibilities=["HR operations, recruiting coordination, employee lifecycle administration, policy support"],
        objectives=["Deliver seamless operational support for candidates and employees"],
        kpis=["Coordination Punctuality", "Record Accuracy Rate"],
        escalation_targets=["hrbp"],
        constraints=["Ensure absolute confidentiality of personal data"],
        elite_domain_mastery=["HR operations", "Recruiting coordination", "Confidentiality and compliance"],
    ),
}

def get_role_by_id(role_id: str) -> Optional[Role]:
    return ALL_ROLES.get(role_id)

def get_subordinates(role_id: str) -> List[Role]:
    return [r for r in ALL_ROLES.values() if r.reports_to == role_id]

def get_ladder_roles(department: str) -> List[Role]:
    return [r for r in ALL_ROLES.values() if r.department.lower() == department.lower()]
